---
title: "Introduction to Data Science"
subtitle: "Section 2 - Prof. Elijah Meyer"
---

## Course overview

Intro to data science and statistical thinking. Learn to explore, visualize, and analyze data to understand natural phenomena, investigate patterns, model outcomes, and make predictions, and do so in a reproducible and shareable manner. Gain experience in data wrangling and munging, exploratory data analysis, predictive modeling, and data visualization, and effective communication of results. Work on problems and case studies inspired by and based on real-world questions and data. The course will focus on the R statistical computing language. No statistical or computing background is necessary. Not open to students who have taken a 100-level Statistical Science course, Statistical Science 210, or a Statistical Science course numbered 300 or above.

## Class meetings

| Meeting | Location                       | Time                        |
|---------|--------------------------------|-----------------------------|
| Lecture | French Science 2231            | Mon & Wed 10:15 - 11:30 am |
| Lab 06  | Perkins Link 087 (Classroom 3) | Thur 10:15 - 11:30 am        |
| Lab 07  | Perkins Link 087 (Classroom 3) | Thur 12:00 - 1:15 pm          |
| Lab 08  | Perkins Link 087 (Classroom 3) | Thur 1:45 - 3:00 pm          |
| Lab 09  | Perkins Link 087 (Classroom 3) | Thur 3:30 - 4:45 pm          |
| Lab 10  | Perkins Link 087 (Classroom 3) | Thur 5:15 - 6:30 pm         |

## Teaching team

| Name                       | Role                  | Lab section         | Office hours                         |
|-----------------|-----------------|-----------------|---------------------|
| Dr. Elijah Meyer  | Instructor            |                     | Tue 10:00 AM - 12:00 PM, Old Chemistry Building 208 / [Zoom](https://bit.ly/3QZ8JAL) / Password: 5MYp7A
| Konnie Huang                 | In Class TA     |                        | Thur 5:00PM - 6:00PM / [Zoom](link)                                                          |
| Eli Gnesin                   | Lab Leader      | Thur 10:15AM - 11:30AM | Thur 9:00AM - 10:00PM \& 12:00 pm - 1:00 pm / [Zoom](link)                                     |
| Yibin Zhang               | Lab Helper              | Thur 10:15AM - 11:30AM   |                                      |
| Caitrin Murphy            | Lab Leader                    | Thur 12:00PM - 1:15PM   | Wed 12:00PM - 2:00 PM / [Zoom](link)                                     |
| Zheyuan Liu               | Lab Helper                    | Thur 12:00PM - 1:15PM   | Thur 1:00PM - 3:00 PM / [Zoom](link)                                      |
| Christine (Yueming) Shen            | Lab Leader / Head TA   | Thur 1:45PM - 3:00PM  | Thur 3:00PM - 5:00 PM / [Zoom](link)                                      |
| Youran Wu                  | Lab Leader                    |   Thur 3:30PM - 4:45PM                  |                                      |
| Mounika Adepu | Lab Helper                    |     Thur 3:30PM - 4:45PM                | Mon 10:30 AM - 12:30 pm / [Zoom](link)                                     |
| Kateryna (Kat) Husar               | Lab Leader        |   Thur 5:15PM - 6:30PM                   |     Tue 12:00PM - 1:00PM \& Wed 5:00PM - 6:00PM / [Zoom](link)                                  |
| Isabella Swigart              | Lab Helper                    |     Thur 5:15PM - 6:30PM      | Tue 4:00 PM - 5:30 PM / [Zoom](link)                                      

