---
title: "Customizing Quarto reports and presentations"
subtitle: "Lecture ??"
date: "November 30th, 2022"
format: revealjs
---

## Checklist

-- Clone `ae-25

## Announcements {.smaller}

-- HW6

-- Exam 1 EC (Done by end of week)

-- Project EC coming 

-- Exam Retake - Released Saturday 

-- Sakai Survey - Due Today 

-- Peer Evaluations - Due Today 

-- Close issues

-- Local R and R-studio

-- Course Evals 



## Course Evaluations - 10 Minutes 

-- Your investment in completing this evaluation thoughtfully for about 10-15 minutes today will not only help instructors improve their courses, but their instruction techniques as well

-- Most of the ratings and responses you provide in your evaluations this semester will be shared with future students. The more students that contribute evaluations, the more access every student will have to course evaluation data when making future course enrollment decisions. 

-- Students will be able to access forms through links in the email reminders, or by logging in to duke.evaluationkit.com.  

## Goals for today 

-- Use color to highlight plot story 

-- Discuss appropriate plot titles 

-- Review Quarto customization tools

-- Any time left will be for project questions

## Close ae-25

-- Run code until you get to `Class starts` section

-- Start creating new variable

## Project Announcements 

-- You are expected to be in lab on December 8th. If there is an extreme circumstance, please get your Dean involved. 

-- The presentation must be no longer than 5 minutes. You can choose to present live in class (recommended) or pre-record a video to be shown in class. 

-- I will have a computer hooked up for presenting. I will pull up your presentation from your hosted website.

## Project Announcements {.smaller}

-- Each individual is expected to be engaged when others are presenting. You will be provided a link, and are expected to will out a review for each presentation. 

-- Things to consider? 

- Well designed research question?

- Appropriate statistical procedures and/or interpretations to answer the question? 

- Any limitations considered? 

- Are slides professional? Is your presentation professional?

- Time management.



