---
title: "Inference + Review"
subtitle: "Lecture 22"
date: "November 14th, 2022"
format: revealjs
---

## Checklist

-- Clone `exam2-review` - This is the part of ae-21 that we didn't finish with end review questions 

## Announcements

-- Exam 2 on Thursday 

- Released at noon 

- No slack or TA office hours 

- Don't cheat 

- due Monday at 2

-- All keys are posted 


## Grading Questions 

-- EC for Exam 1 is not in 

-- Lowest HW is dropped 

-- Lowest Lab is dropped 


## Study Tips - Variables 

-- Identify variables

- Categorical vs Quantitative 

- Explanatory vs Response 

## Models by Variable Type{.smaller} 

-- Simple Linear Regression: 1 Quantitative Response; 1 Categorical or Quantitative Explanatory Variable 

-- Mulitple Linear Regression: 1 Quantitative Response; 2 or more Categorical or Quantitative Explanatory Variables

-- Logistic Regression: 1 Categorical Response (Binary); 1 or more Categorical or Quantitative Explanatory Variables

## Study Tips - Make your own guide

```{r}
#| eval: false
abb |>    
  summarize(ppg.mean = mean(ppg)) #Summarize is used to calculate a summary statistic 
                                  #arguments: new name = calculated statistic

?summarize 

```

Reference *Examples* at bottom of help page, AEs, HWs, and Labs.

## Goals

-- Review 

- Simpson's Paradox 

- P-value interpretation  

-- Compare two means, and do a bootstrap interval

-- Prediction and bootstrap interval for the slope



