{
  "hash": "fc7d6a1bf2bdf56f127588653dd32b5c",
  "result": {
    "markdown": "---\ntitle: \"Regression with Multiple Predictors\"\nformat: html\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\nlibrary(plotly)\nlibrary(widgetframe)\n```\n:::\n\n\nToday, we will expand our understanding of models by continuing to learn about penguins. In the last class, we modeled body mass by flipper length, and in a separate model, modeled body mass by island. Could it be possible that the estimated body mass of a penguin changes by both their flipper length AND by the island they are on?\n\nReview: Take a `glimpse` at the data set before we get started. The data set is called `penguins`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n:::\n:::\n\n\nNow, fit a model to assess the relationship between our response variable body mass, and our explanatory variables flipper length and island. Produce the summary output. Write out the estimate regression equation below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm + island, data = penguins) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        -4625.     392.      -11.8  4.29e-27\n2 flipper_length_mm     44.5      1.87     23.9  1.65e-74\n3 islandDream         -262.      55.0      -4.77 2.75e- 6\n4 islandTorgersen     -185.      70.3      -2.63 8.84e- 3\n```\n:::\n:::\n\n$$\\hat{body.mass = -4625 + 44.5*flipper  - 262*Dream - 185* Torgersen}$$ \\\\\n\nDream = 1 if Dream; 0 else \\\\ Torgersen = 1 if Torgersen; 0 else \n\nIs this an additive model or an interaction model? **Additive model**\n\nLet's visualize what these estimates represent.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Code to get predicted values \nmodel1 <- lm(body_mass_g ~ flipper_length_mm + island, data = penguins)\np <- predict(model1)\n\nclean_penguins <- penguins |> \n  drop_na(flipper_length_mm)\n\nclean_penguins <- cbind(p, clean_penguins)\n\n\n#Code to visualize model output\n\nclean_penguins |>\n  ggplot(\n    aes(x = flipper_length_mm, y = body_mass_g, color = island)\n  ) + \n  geom_point(alpha = 0.2) + \n  geom_line(\n    aes(y = p), \n    linetype = \"dashed\",\n    lwd = 1.5\n    \n  ) + \n  labs( \n    x = \"Flipper Length mm\", \n    y = \"Body Mass g\", \n    title = \"Additive Model\",\n    color = \"Island\")\n```\n\n::: {.cell-output-display}\n![](ae-16-A_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n-- Interpret the slope coefficient for flipper length in the context of the problem\n\nFor every 1 mm increase in flipper length, we estimate on average a 44.5 g increase in body mass, after holding all other variables constant\n\n-- Predict the body mass of a penguin with a flipper length of 200 on the Dream island\n\n\n\n\n$$\\hat{body.mass = -4625 + 44.5*200  - 262*1 - 185* 0}$$\n\n\n\nReview: Look at the plot you created. What assumption does the additive model make about the slopes between flipper length and body mass for each of the three islands?\n\nThe additive model assumes the same slope between body mass and flipper length for all three islands.\n\n## Interaciton Model\n\nWhat changes in the R code when fitting an interaction model instead of an additive model in R? We change the + to a \\*\n\n-- Now fit the interaction model. Display the summary output and write out the estimate regression equation below.\n\n::: {.cell}\n\n```{.r .cell-code}\n  linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm * island, data = penguins) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  term                              estimate std.error statistic  p.value\n  <chr>                                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                        -5464.     431.      -12.7  2.51e-30\n2 flipper_length_mm                     48.5      2.05     23.7  1.66e-73\n3 islandDream                         3551.     969.        3.66 2.89e- 4\n4 islandTorgersen                     3218.    1680.        1.92 5.62e- 2\n5 flipper_length_mm:islandDream        -19.4      4.94     -3.93 1.03e- 4\n6 flipper_length_mm:islandTorgersen    -17.4      8.73     -1.99 4.69e- 2\n```\n:::\n:::\n\n\n\n$$\\hat{body.mass} = -5464 + 48.5*flipper + 3551*Dream + 3218*Torgersen - 19.4*Dream*flipper - 17.4*Torgersen\\*flipper$$\n\n\n\nLet's visualize what these estimates represent.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Code to get predicted values \nmodel2 <- lm(body_mass_g ~ flipper_length_mm*island, data = penguins)\np2 <- predict(model2)\n\nclean_penguins2 <- penguins |> \n  drop_na(flipper_length_mm)\n\nclean_penguins <- cbind(p2, clean_penguins)\n\n\n#Code to visualize model output\n\nclean_penguins2 |>\n  ggplot(\n    aes(x = flipper_length_mm, y = body_mass_g, color = island)\n  ) + \n  geom_point(alpha = 0.2) + \n  geom_line(\n    aes(y = p2), \n    linetype = \"dashed\",\n    lwd = 1.5\n    \n  ) + \n  labs( \n    x = \"Flipper Length mm\", \n    y = \"Body Mass g\", \n    title = \"Interaction Model\",\n    color = \"Island\")\n```\n\n::: {.cell-output-display}\n![](ae-16-A_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n-- Interpret the interaction term for flipper length and Dream island in the context of the problem.\n\nThe rate of change between estimated body mass and flipper length, on average is different between dream island and biscoe island.\n\n-- Predict the body mass of a penguin with a flipper length of 200 on the Dream island\n\n\n\n\n$$\\hat{body.mass} = -5464 + 48.5*200 + 3551*1 + 3218*0 - 19.4*1*flipper - 17.4*0*200$$\n\n\n\n\n## How can we choose?\n\nOccam's Razor - Don't overcomplicate the situation. We prefer the *simplest* best model.\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7742334\n```\n:::\n\n```{.r .cell-code}\nglance(model2)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7857486\n```\n:::\n\n```{.r .cell-code}\nglance(model1)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7722296\n```\n:::\n\n```{.r .cell-code}\nglance(model2)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7825604\n```\n:::\n:::\n\n-- What is R-squared? What is adjusted R-squared?\n\nR-squared is the percent variability in the response that is explained by our model. (Can use when models have same number of variables for model selection)\n\nAdjusted R-squared is similar, but has a penalty for the number of variables in the model. (Should use for model selection when models have different numbers of variables).\n\n## Two Quantitative Explanatory Variables\n\nNow, let's explore body mass, and it's relationship to bill length and flipper length.\n\n-- Brainstorm, how could we visualize this?\n\nNote: This code is beyond the scope of this course!\n\n::: {.cell}\n\n```{.r .cell-code}\nquanplot <- plot_ly(penguins, \n                    x = ~ flipper_length_mm, y = ~ bill_length_mm, z = ~body_mass_g,\n                    marker = list(size = 3, color = \"lightgray\" , alpha = 0.5, \n                                  line = list(color = \"gray\" , width = 2))) |>\n                      add_markers() |>\n                      plotly::layout(scene = list(\n                        xaxis = list(title = \"Flipper (mm)\"),\n                        yaxis = list(title = \"Bill (mm)\"), \n                        zaxis = list(title = \"Body Mass (g)\")\n                      )) |>\n                    config(displayModeBar = FALSE)\n                  frameWidget(quanplot)\n```\n:::\n\n-- Fit the additive model below. Interpret the coefficient for flipper in context of the problem.\n\n::: {.cell}\n\n```{.r .cell-code}\n  linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm + bill_length_mm, data = penguins) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)       -5737.      308.      -18.6  7.80e-54\n2 flipper_length_mm    48.1       2.01     23.9  7.56e-75\n3 bill_length_mm        6.05      5.18      1.17 2.44e- 1\n```\n:::\n:::\n\nHolding all other variables constant, for every one mm increase in flipper length, we expect on average a 48.1 mm increase in estimated body mass.\n\nWhat if I want to fit an interaction model with these two quantitative variables?\n\nIt looks really similar to what we've done before! Try it out!\n",
    "supporting": [
      "ae-16-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}