{
  "hash": "ed4cb27a983cb3e870b7eefda414f128",
  "result": {
    "markdown": "---\ntitle: \"Regression with a Single Predictor\"\nformat: html\neditor: visual\n---\n\n\nBefore getting started, make sure that these two packages are installed:\n\n`palmerpenguins` and `tidymodels`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\n```\n:::\n\n\nToday, we will be studying penguins. Please read the following context and take a `glimpse` at the data set before we get started.\n\nThis data set comprising various measurements of three different penguin species, namely Adelie, Gentoo, and Chinstrap. The rigorous study was conducted in the islands of the Palmer Archipelago, Antarctica. These data were collected from 2007 to 2009 by Dr. Kristen Gorman with the Palmer Station Long Term Ecological Research Program, part of the US Long Term Ecological Research Network. The data set is called `penguins`.\n\n-   Take a glimpse of the data set below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n:::\n:::\n\n\nWe want to understand more about a penguin's body mass. First, we are going to investigate the relationship between a penguin's flipper length and their body mass.\n\n-   Based on our research question, which variable is the response variable?\n\n**body mass**\n\n-   Now, visualize the relationship between the two variables. Describe the plot created.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  ggplot( \n    aes(y = body_mass_g, x = flipper_length_mm)) + \n  geom_point() + \n  geom_smooth(method = \"lm\" , fullrange = T) + \n  xlim(0,240)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing non-finite values (stat_smooth).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![](ae-15-A_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Model these Data\n\n-   Write the population model below that explains the relationship between body mass and flipper length. Hint: You can type equations within dollar sign code chunks seen below.\n\n\\$\\$\n\nbeta\n\n\\hat{} \\<- put a hat on \\\\\n\n\\beta \\<- this is beta\n\n{ }\n\n\\$\\$\n\n-   Now, fit the linear regression model and display the results. Write the estimated model output below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm, data = penguins) |>\n  tidy()\n```\n:::\n\n\n\\$\\$\n\n\\hat{Body Mass} = -5781 + 49.7\\*(flipper) \\\\\n\nBodyMass = \\beta\\_o + \\beta\\_1\\*flipper + \\epsilon\\_i\n\n\\$\\$\n\n-   Interpret the slope and the intercept in the context of the data.\n\nSlope: \"A 1 unit increase in x\" \"on average\"\n\nFor a 1 mm increase in flipper length, we expect **on average** an estimated 49.7 gram increase is body mass.\n\nIntercept: When flipper length is 0, we estimate on average a body mass of -5791 grams.\n\n-   What is the estimated body mass for a penguin with a flipper length of 210?\n\n\\hat{Body Mass} = -5781 + 49.7\\*(200) \n\n\\hat{Body Mass} = -5781 + 49.7\\*(100)\n\n-   What is the estimated body mass for a penguin with a flipper length of 100?\n\n## Next Question\n\n-   Now, we will investigate another question. A different researcher wants to look at body weight of penguins based on the island they were recorded on. What's different between this question and the last? Hint: Think about the variable type.\n\n**Our explanatory variable is now categorical**\n\n-   Make an appropriate visualization to investigate this relationship below. Additionally, calculate the mean body mass by island below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  ggplot(\n    aes(y = body_mass_g, x = island)\n  ) + \n  geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![](ae-15-A_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n-   Change the geom of your previous plot to geom_point. Use this plot to think about how R models these data.\n\n**The minimize the residuals within each group, our model should go through the mean! Not only does this minimize the residual sums of squares, but it also logically is our best guessed for a random penguin body mass.**\n\n-   Now, fit the linear regression model and display the results. Write the estimated model output below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ island, data = penguins) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        4716.      48.5      97.3 8.93e-250\n2 islandDream       -1003.      74.2     -13.5 1.42e- 33\n3 islandTorgersen   -1010.     100.      -10.1 4.66e- 21\n```\n:::\n:::\n\n\n-   Interpret each coefficient below in the context of the problem.\n\n-   What is the estimated body weight of a penguin on Dream island?\n\nThe estimated body mass of a penguin, on average, that is located on the dream island is (4716 - 1003)g.\n\n-   What is the estimated body weight of a penguin on Biscoe island?\n\nThe estimated body mass of a penguin, on average, that is located on the Biscoe islad is 4716 g.\n\n## Optional\n\nAsk your own question and explore it!\n",
    "supporting": [
      "ae-15-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}